### ISSUE TITLE
Compiling failed on M1 Mac OS 14.5

### ISSUE THREAD

**Issue by gwythan** [arcanebyte/lisaem#7]
Hi,

I followed the README instructions for compiling on the Mac. I got 1 warning and 2 failures for the below listed command line instructions:

_$ git clone https://github.com/arcanebyte/lisaem_

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'share/LisaEm'
  'share/lisaem'

```

$  ./build.sh clean build

```
---------------------------- /tmp/slot.12226.53.failure -------------------------------
 gcc -W -w -Wstrict-prototypes -Wno-format -Wno-unused -I/usr/local/wx3.2.5-cocoa-macOS-14.5-x86_64,arm64/lib/wx/include/osx_cocoa-unicode-static-3.2 -I/usr/local/wx3.2.5-cocoa-macOS-14.5-x86_64,arm64/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ -fno-common -fPIC -fwrapv -fno-strict-aliasing -Wno-write-strings -O2 -ffast-math -fomit-frame-pointer -std=c99 -mmacosx-version-min=14.5.0 -Wno-format-truncation -Wno-unknown-warning-option -m64 -I /Users/dev/lisaem/wxWidgets-3.2.5/include -I /Users/dev/lisaem/wxWidgets-3.2.5/3rdparty/catch/include -I /Users/dev/lisaem/wxWidgets-3.2.5/build-cocoa-macOS-14.5-clang-sdl/lib/wx/include -I /Users/dev/lisaem/wxWidgets-3.2.5/src/stc/scintilla/include -I /Users/dev/lisaem/src/tools/include -I /Users/dev/lisaem/src/host/wxui/include -I /Users/dev/lisaem/src/include -I /Users/dev/lisaem/src/printer/imagewriter/include -I /Users/dev/lisaem/src/lisa/crt/hqx/include -I /Users/dev/lisaem/src/lisa/keyboard/include -I /Users/dev/lisaem/src/lib/libdc42/include -I /Users/dev/lisaem/src/lib/libdc42/tester/src/include -I /Users/dev/lisaem/src/lib/libdc42/src/include -I /Users/dev/lisaem/src/lib/libGenerator/include -I /Users/dev/lisaem/src/lib/libGenerator/src/include -I /Users/dev/lisaem/src/lib/TerminalWx/src/include -c src/lisa/io_board/z8530.c -o obj/z8530.o
in: /Users/dev/lisaem

!!  Compiled src/lisa/io_board/z8530.c...
src/lisa/io_board/z8530.c:663:37: error: incompatible function pointer types assigning to 'char (*)(unsigned int)' from 'char (int)' [-Wincompatible-function-pointer-types]
      scc_fn[port].read_serial_port = read_serial_port_terminal;
                                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
src/lisa/io_board/z8530.c:664:38: error: incompatible function pointer types assigning to 'void (*)(unsigned int, char)' from 'void (int, uint8)' (aka 'void (int, unsigned char)') [-Wincompatible-function-pointer-types]
      scc_fn[port].write_serial_port = write_serial_port_terminal;
                                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
see: /tmp/slot.12226.53.sh /tmp/slot.12226.53.sh.failed for details
failed command was: gcc -W -w -Wstrict-prototypes -Wno-format -Wno-unused -I/usr/local/wx3.2.5-cocoa-macOS-14.5-x86_64,arm64/lib/wx/include/osx_cocoa-unicode-static-3.2 -I/usr/local/wx3.2.5-cocoa-macOS-14.5-x86_64,arm64/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ -fno-common -fPIC -fwrapv -fno-strict-aliasing -Wno-write-strings -O2 -ffast-math -fomit-frame-pointer -std=c99 -mmacosx-version-min=14.5.0 -Wno-format-truncation -Wno-unknown-warning-option -m64 -I /Users/dev/lisaem/wxWidgets-3.2.5/include -I /Users/dev/lisaem/wxWidgets-3.2.5/3rdparty/catch/include -I /Users/dev/lisaem/wxWidgets-3.2.5/build-cocoa-macOS-14.5-clang-sdl/lib/wx/include -I /Users/dev/lisaem/wxWidgets-3.2.5/src/stc/scintilla/include -I /Users/dev/lisaem/src/tools/include -I /Users/dev/lisaem/src/host/wxui/include -I /Users/dev/lisaem/src/include -I /Users/dev/lisaem/src/printer/imagewriter/include -I /Users/dev/lisaem/src/lisa/crt/hqx/include -I /Users/dev/lisaem/src/lisa/keyboard/include -I /Users/dev/lisaem/src/lib/libdc42/include -I /Users/dev/lisaem/src/lib/libdc42/tester/src/include -I /Users/dev/lisaem/src/lib/libdc42/src/include -I /Users/dev/lisaem/src/lib/libGenerator/include -I /Users/dev/lisaem/src/lib/libGenerator/src/include -I /Users/dev/lisaem/src/lib/TerminalWx/src/include -c src/lisa/io_board/z8530.c -o obj/z8530.o
from: /Users/dev/lisaem
--------------------- Compilation Aborted ---------------------

```

Environment:

Apple M1 Pro laptop, 16MB RAM
Mac OS Sonoma 14.5
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix

Kind regards,
Kevin.

**Comment by arcanebyte** [comment]
Thanks for the report. I'm also using an M1 w/ 14.5, so I will check this out and let ya know. I might revert wx3.2.5 changes due to a possible bug. Stand by.

**Comment by arcanebyte** [comment]
Confirmed this error on a clean deployment of macOS 14.6 w/ xcode 15.4. Thanks for the report.

**Comment by arcanebyte** [comment]
So, turns out this is less of an M1 issue but rather more of a "xcode > 14.1 became more strict in type mismatches" issue. Compiled fine on my M1 w/ macOS 14.5 and xcode 14.1, and failed on an M1 with 14.6 and xcode 14.5. The compiler has identified some type mismatches between char and uint8 and int and unsigned int. I've patched things to get it to compile, but we have no unit or functional tests to ensure it didn't break something. Ray was strict about wanting to keep the code updated to standard rather than using compiler flags to be less strict or follow an older standard, so I'll need to dig a little more to make sure what I've done won't bust things.

**Comment by arcanebyte** [comment]
@gwythan I have pushed some changes to the master branch if you want to try and compile again. I recommend not using wxWidgets 3.2.5 at this time, maybe [build-wx3.1.5-modern-macosx.sh](https://github.com/arcanebyte/lisaem/blob/master/scripts/build-wx3.1.5-modern-macosx.sh) would be best for better mouse compatibility.

**Comment by gwythan** [comment]
Hi. Yes, I can confirm that LisaEm is now compiling on my system! THANK YOU.

Note: I'm still getting a warmning about mixed case in some compiler paths — as I reported in this ticket — which I believe shoukd be easy to rectify:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'share/LisaEm'
  'share/lisaem'
```


I have not been able to successfult boot the emulator, but I'll open a ticket separately for that.
